# Generated by Django 4.0.3 on 2022-06-07 15:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('technology', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(choices=[('New South Wales', 'New South Wales'), ('Victoria', 'Victoria'), ('Queensland', 'Queensland'), ('South Australia', 'South Australia'), ('Western Australia', 'Western Australia'), ('Tasmania', 'Tasmania'), ('Northern Territory', 'Northern Territory'), ('Australian Capital Territory', 'Australian Capital Territory')], max_length=50, null=True)),
                ('industry', models.CharField(choices=[('Accounting', 'Accounting'), ('Administration & Office Support', 'Administration & Office Support'), ('Advertising, Arts & Media', 'Advertising, Arts & Media'), ('Banking & Financial Services', 'Banking & Financial Services'), ('Call Centre & Customer Service', 'Call Centre & Customer Service'), ('CEO & General Management', 'CEO & General Management'), ('Community Services & Development', 'Community Services & Development'), ('Construction', 'Construction'), ('Consulting & Strategy', 'Consulting & Strategy'), ('Design & Architecture', 'Design & Architecture'), ('Education & Training', 'Education & Training'), ('Engineering', 'Engineering'), ('Farming, Animals & Conservation', 'Farming, Animals & Conservation'), ('Government & Defence', 'Government & Defence'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Human Resources & Recruitment', 'Human Resources & Recruitment'), ('Information & Communication Technology', 'Information & Communication Technology'), ('Insurance & Superannuation', 'Insurance & Superannuation'), ('Legal', 'Legal'), ('Manufacturing, Transport & Logistics', 'Manufacturing, Transport & Logistics'), ('Marketing & Communications', 'Marketing & Communications'), ('Mining, Resources & Energy', 'Mining, Resources & Energy'), ('Real Estate & Property', 'Real Estate & Property'), ('Retail & Consumer Products', 'Retail & Consumer Products'), ('Sales', 'Sales'), ('Science & Technology', 'Science & Technology'), ('Self Employment', 'Self Employment'), ('Sport & Recreation', 'Sport & Recreation'), ('Trades & Services', 'Trades & Services')], max_length=50, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
