# Generated by Django 4.0.3 on 2022-05-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='age',
        ),
    ]
