# Generated by Django 4.0.3 on 2022-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Administration & Office Support', 'Administration & Office Support'), ('Advertising, Arts & Media', 'Advertising, Arts & Media'), ('Banking & Financial Services', 'Banking & Financial Services'), ('Call Centre & Customer Service', 'Call Centre & Customer Service'), ('CEO & General Management', 'CEO & General Management'), ('Community Services & Development', 'Community Services & Development'), ('Construction', 'Construction'), ('Consulting & Strategy', 'Consulting & Strategy'), ('Design & Architecture', 'Design & Architecture'), ('Education & Training', 'Education & Training'), ('Engineering', 'Engineering'), ('Farming, Animals & Conservation', 'Farming, Animals & Conservation'), ('Government & Defence', 'Government & Defence'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Human Resources & Recruitment', 'Human Resources & Recruitment'), ('Information & Communication Technology', 'Information & Communication Technology'), ('Insurance & Superannuation', 'Insurance & Superannuation'), ('Legal', 'Legal'), ('Manufacturing, Transport & Logistics', 'Manufacturing, Transport & Logistics'), ('Marketing & Communications', 'Marketing & Communications'), ('Mining, Resources & Energy', 'Mining, Resources & Energy'), ('Real Estate & Property', 'Real Estate & Property'), ('Retail & Consumer Products', 'Retail & Consumer Products'), ('Sales', 'Sales'), ('Science & Technology', 'Science & Technology'), ('Self Employment', 'Self Employment'), ('Sport & Recreation', 'Sport & Recreation'), ('Trades & Services', 'Trades & Services')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('New South Wales', 'New South Wales'), ('Victoria', 'Victoria'), ('Queensland', 'Queensland'), ('South Australia', 'South Australia'), ('Western Australia', 'Western Australia'), ('Tasmania', 'Tasmania'), ('Northern Territory', 'Northern Territory'), ('Australian Capital Territory', 'Australian Capital Territory')], max_length=50, null=True),
        ),
    ]
